version: '3.8'

services:
  backend:
    build:
      context: ./be_chatapp
    container_name: backend
    depends_on:
      - db
    ports:
      - "3000:3000"
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./fe_chatapp
    container_name: frontend
    ports:
      - "5731:5731"
    depends_on:
      - backend
    networks:
      - app-network

  db:
    container_name: postgres_chatapp
    image: postgres
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: chatapp
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local
